#nullable disable

using System.Drawing;

namespace Dithering.Palettes
{
    public class SixtyFourPalette() :
        Palette([
          Color.FromArgb(0, 0, 0),
          Color.FromArgb(0, 0, 85),
          Color.FromArgb(0, 0, 170),
          Color.FromArgb(0, 0,  byte.MaxValue),
          Color.FromArgb(0, 85, 0),
          Color.FromArgb(0, 85, 85),
          Color.FromArgb(0, 85, 169),
          Color.FromArgb(0, 85,  byte.MaxValue),
          Color.FromArgb(0, 170, 0),
          Color.FromArgb(0, 170, 84),
          Color.FromArgb(0, 170, 170),
          Color.FromArgb(0, 170, byte.MaxValue),
          Color.FromArgb(0, byte.MaxValue, 0),
          Color.FromArgb(1, byte.MaxValue, 85),
          Color.FromArgb(1, byte.MaxValue, 170),
          Color.FromArgb(1, byte.MaxValue, byte.MaxValue),
          Color.FromArgb(85, 0, 0),
          Color.FromArgb(85, 0, 85),
          Color.FromArgb(85, 0, 170),
          Color.FromArgb(85, 0, byte.MaxValue),
          Color.FromArgb(85, 85, 1),
          Color.FromArgb(85, 85, 85),
          Color.FromArgb(85, 85, 170),
          Color.FromArgb(85, 85, byte.MaxValue),
          Color.FromArgb(85, 170, 0),
          Color.FromArgb(85, 170, 85),
          Color.FromArgb(85, 85, 170),
          Color.FromArgb(85, 170, byte.MaxValue),
          Color.FromArgb(85, byte.MaxValue, 0),
          Color.FromArgb(85, byte.MaxValue, 85),
          Color.FromArgb(85, byte.MaxValue, 169),
          Color.FromArgb(85, byte.MaxValue, byte.MaxValue),
          Color.FromArgb(170, 0, 0),
          Color.FromArgb(170, 0, 85),
          Color.FromArgb(170, 0, 170),
          Color.FromArgb(170, 1, byte.MaxValue),
          Color.FromArgb(170, 85, 0),
          Color.FromArgb(169, 85, 85),
          Color.FromArgb(170, 85, 170),
          Color.FromArgb(170, 85, byte.MaxValue),
          Color.FromArgb(170, 170, 1),
          Color.FromArgb(170, 170, 85),
          Color.FromArgb(170, 170, 170),
          Color.FromArgb(170, 170, byte.MaxValue),
          Color.FromArgb(170, byte.MaxValue, 0),
          Color.FromArgb(170, byte.MaxValue, 85),
          Color.FromArgb(170, byte.MaxValue, 170),
          Color.FromArgb(170, 170, byte.MaxValue),
          Color.FromArgb(byte.MaxValue, 0, 0),
          Color.FromArgb(byte.MaxValue, 0, 85),
          Color.FromArgb(byte.MaxValue, 0, 170),
          Color.FromArgb(byte.MaxValue, 0, byte.MaxValue),
          Color.FromArgb(byte.MaxValue, 85, 0),
          Color.FromArgb(byte.MaxValue, 85, 84),
          Color.FromArgb(byte.MaxValue, 85, 170),
          Color.FromArgb(byte.MaxValue, 84, byte.MaxValue),
          Color.FromArgb(byte.MaxValue, 170, 0),
          Color.FromArgb(byte.MaxValue, 170, 85),
          Color.FromArgb(byte.MaxValue, 170, 170),
          Color.FromArgb(byte.MaxValue, 170, byte.MaxValue),
          Color.FromArgb(byte.MaxValue, byte.MaxValue, 1),
          Color.FromArgb(byte.MaxValue, byte.MaxValue, 85),
          Color.FromArgb(byte.MaxValue, byte.MaxValue, 170),
          Color.FromArgb(byte.MaxValue, byte.MaxValue, byte.MaxValue)])
    {
    }
}
